title: Therapy Cove
description: Σύγχρονο κέντρο ψυχικής υγείας στην Αθήνα.
baseurl: ""
url: "https://www.therapycove.gr"
permalink: pretty
lang: "gr"
logo: "/assets/images/therapy-cove-logo.png"
image: "/assets/images/therapy-cove-space-hero.jpg"
flags:
  show_lang_toggle: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-polyglot
languages:
  - "gr"
  - "en"
default_lang: "gr"
exclude_from_localization:
  - "assets"
  - "admin"
  - "scripts"
  - "cloudflare"
  - "node_modules"
  - "vendor"
  - ".bundle"
  - ".idea"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  - "README.md"
parallel_localization: false
defaults:
  - scope:
      path: "admin"
    values:
      sitemap: false
exclude:
  - ".idea/"
  - "node_modules/"
  - "cloudflare/"
  - "vendor/"
  - ".bundle/"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  - "craco.config.js"
  - "src/"
  - "public/"
  - "locales/"
  - "README.md"
