title: Therapy Cove
description: Secure, personalized online therapy in Greece.
baseurl: ""
url: "https://www.therapycove.gr"
permalink: pretty
lang: "el"
plugins:
  - jekyll-seo-tag
  - jekyll-polyglot
languages:
  - "el"
  - "en"
default_lang: "el"
exclude_from_localization:
  - "assets"
  - "admin"
  - "scripts"
  - "node_modules"
  - "vendor"
  - ".bundle"
  - ".idea"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  - "README.md"
parallel_localization: false
exclude:
  - ".idea/"
  - "node_modules/"
  - "vendor/"
  - ".bundle/"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  - "craco.config.js"
  - "src/"
  - "public/"
  - "locales/"
  - "README.md"
