title: Therapy Cove
description: Secure, personalized online therapy in Greece.
baseurl: ""
url: "https://www.therapycove.gr"
permalink: pretty
lang: "el"
plugins:
  - jekyll-seo-tag
exclude:
  - ".idea/"
  - "node_modules/"
  - "vendor/"
  - ".bundle/"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  - "craco.config.js"
  - "src/"
  - "public/"
  - "locales/"
  - "README.md"